import { createContext, useContext, useEffect, useState, ReactNode } from 'react';
import { User, Session } from '@supabase/supabase-js';
import { supabase } from '@/integrations/supabase/client';
import { setActiveCompanyId } from '@/lib/companyScope';
import { applyBrand } from '@/lib/branding';

const GERAL_SECTOR_ID='00000000-0000-0000-0000-000000000001';
const PROFILE_CACHE_PREFIX='nuvexa:profile:';
const COMPANY_CACHE_PREFIX='nuvexa:company:';
interface Profile{id:string;user_id:string;name:string;display_name:string|null;email:string;avatar_url:string|null;sector_id:string|null;autonomy_level:string;birth_date:string|null;is_active:boolean;profile_type:string;created_at:string;updated_at:string;last_seen_at:string|null;user_status:string|null;work_period:string|null;company_id:string;}
interface Sector{id:string;name:string;color:string;icon:string|null;}
interface UserRole{role:'admin'|'gerente'|'supervisor'|'colaborador';}
interface UserPermissions{can_post_announcements:boolean;can_delete_messages:boolean;can_access_management:boolean;can_access_password_change:boolean;can_create_war_room:boolean;can_access_bh:boolean;can_access_fechamento:boolean;can_access_orbs:boolean;}
interface AuthContextType{user:User|null;session:Session|null;profile:Profile|null;sector:Sector|null;additionalSectors:Sector[];allAccessibleSectorIds:string[];roles:UserRole[];permissions:UserPermissions|null;isAdmin:boolean;geralSectorId:string;loading:boolean;verifying:boolean;setVerifying:(v:boolean)=>void;signIn:(email:string,password:string)=>Promise<{error:Error|null}>;signOut:()=>Promise<void>;refreshProfile:()=>Promise<void>;refreshPermissions:()=>Promise<void>;canAccess:(permission:keyof UserPermissions)=>boolean;hasSectorAccess:(sectorId:string)=>boolean;}
const defaultPermissions:UserPermissions={can_post_announcements:false,can_delete_messages:false,can_access_management:false,can_access_password_change:false,can_create_war_room:false,can_access_bh:false,can_access_fechamento:false,can_access_orbs:false};
const AuthContext=createContext<AuthContextType|undefined>(undefined);
const readCachedProfile=(userId:string):Profile|null=>{try{const raw=localStorage.getItem(`${PROFILE_CACHE_PREFIX}${userId}`);if(!raw)return null;const p=JSON.parse(raw) as Profile;return p?.user_id===userId&&p?.company_id?p:null;}catch{return null;}};
const cacheProfile=(p:Profile)=>{try{localStorage.setItem(`${PROFILE_CACHE_PREFIX}${p.user_id}`,JSON.stringify(p));}catch{}};
const readCachedCompany=(id:string):any|null=>{try{const raw=localStorage.getItem(`${COMPANY_CACHE_PREFIX}${id}`);if(!raw)return null;const c=JSON.parse(raw);return c?.id===id&&c?.primary_color&&c?.secondary_color?c:null;}catch{return null;}};
const cacheCompany=(c:any)=>{try{localStorage.setItem(`${COMPANY_CACHE_PREFIX}${c.id}`,JSON.stringify(c));}catch{}};

export function AuthProvider({children}:{children:ReactNode}){
 const[user,setUser]=useState<User|null>(null);const[session,setSession]=useState<Session|null>(null);const[profile,setProfile]=useState<Profile|null>(null);const[sector,setSector]=useState<Sector|null>(null);const[additionalSectors,setAdditionalSectors]=useState<Sector[]>([]);const[roles,setRoles]=useState<UserRole[]>([]);const[permissions,setPermissions]=useState<UserPermissions|null>(null);const[loading,setLoading]=useState(true);const[verifying,setVerifying]=useState(false);const isAdmin=roles.some(r=>r.role==='admin');const allAccessibleSectorIds=[GERAL_SECTOR_ID,...(profile?.sector_id?[profile.sector_id]:[]),...additionalSectors.map(s=>s.id)];
 const fetchPermissions=async(userId:string)=>{try{const{data,error}=await supabase.from('user_permissions').select('*').eq('user_id',userId).maybeSingle();if(error){console.error('Error fetching permissions:',error);return;}if(data)setPermissions({can_post_announcements:data.can_post_announcements,can_delete_messages:data.can_delete_messages,can_access_management:data.can_access_management,can_access_password_change:data.can_access_password_change,can_create_war_room:data.can_create_war_room,can_access_bh:(data as any).can_access_bh??false,can_access_fechamento:(data as any).can_access_fechamento??false,can_access_orbs:(data as any).can_access_orbs??false});else setPermissions(defaultPermissions);}catch(error){console.error('Error in fetchPermissions:',error);setPermissions(defaultPermissions);}};
 const fetchAdditionalSectors=async(userId:string)=>{try{const{data:additionalData,error:additionalError}=await supabase.from('user_additional_sectors').select('sector_id').eq('user_id',userId);if(additionalError){console.error('Error fetching additional sectors:',additionalError);return;}if(additionalData?.length){const ids=additionalData.map(d=>d.sector_id);const{data:sectorsData,error:sectorsError}=await supabase.from('sectors').select('*').in('id',ids);if(sectorsError){console.error('Error fetching sector details:',sectorsError);return;}if(sectorsData)setAdditionalSectors(sectorsData as Sector[]);}else setAdditionalSectors([]);}catch(error){console.error('Error in fetchAdditionalSectors:',error);setAdditionalSectors([]);}};
 const hydrateCompanyBrand=async(companyId:string)=>{const cached=readCachedCompany(companyId);if(cached){applyBrand(cached);return;}const{data,error}=await(supabase as any).from('companies').select('id,name,slug,logo_url,primary_color,secondary_color,is_active,is_system,enabled_modules').eq('id',companyId).maybeSingle();if(!error&&data){cacheCompany(data);applyBrand(data);}};
 const fetchProfile=async(userId:string)=>{try{
   // Obtemos o company_id em uma consulta leve e independente, em paralelo ao perfil completo.
   // Assim a identidade visual nao fica presa ao RPC mais pesado.
   const companyIdPromise=(supabase as any).from('profiles').select('company_id').eq('user_id',userId).maybeSingle();
   const profilePromise=supabase.rpc('get_my_full_profile');
   const[{data:companyRef},{data:profileRows,error:profileError}]=await Promise.all([companyIdPromise,profilePromise]);
   const earlyCompanyId=companyRef?.company_id as string|undefined;
   if(earlyCompanyId){setActiveCompanyId(earlyCompanyId);await hydrateCompanyBrand(earlyCompanyId);}
   if(profileError){console.error('Error fetching profile:',profileError);return;}
   const profileData=Array.isArray(profileRows)?profileRows[0]:profileRows;
   if(profileData){const nextProfile=profileData as Profile;cacheProfile(nextProfile);setProfile(nextProfile);setActiveCompanyId(nextProfile.company_id??earlyCompanyId??null);if(nextProfile.company_id&&nextProfile.company_id!==earlyCompanyId)await hydrateCompanyBrand(nextProfile.company_id);if(nextProfile.sector_id){const{data:sectorData}=await supabase.from('sectors').select('*').eq('id',nextProfile.sector_id).maybeSingle();if(sectorData)setSector(sectorData as Sector);}}
   const{data:rolesData,error:rolesError}=await supabase.from('user_roles').select('role').eq('user_id',userId);if(rolesError)console.error('Error fetching roles:',rolesError);else if(rolesData)setRoles(rolesData as UserRole[]);
   await Promise.all([fetchAdditionalSectors(userId),fetchPermissions(userId)]);
 }catch(error){console.error('Error in fetchProfile:',error);}};
 const hydrateCachedProfile=(userId:string)=>{const cached=readCachedProfile(userId);if(!cached)return false;setProfile(cached);setActiveCompanyId(cached.company_id);const company=readCachedCompany(cached.company_id);if(company)applyBrand(company);else void hydrateCompanyBrand(cached.company_id);return true;};
 const refreshProfile=async()=>{if(user)await fetchProfile(user.id)};const refreshPermissions=async()=>{if(user)await fetchPermissions(user.id)};const canAccess=(permission:keyof UserPermissions)=>isAdmin||Boolean(permissions?.[permission]);const hasSectorAccess=(sectorId:string)=>isAdmin||allAccessibleSectorIds.includes(sectorId);
 useEffect(()=>{const{data:{subscription}}=supabase.auth.onAuthStateChange((event,session)=>{setSession(session);setUser(session?.user??null);if(session?.user){hydrateCachedProfile(session.user.id);setTimeout(()=>fetchProfile(session.user.id),0);}else{setProfile(null);setActiveCompanyId(null);setSector(null);setAdditionalSectors([]);setRoles([]);setPermissions(null);}});supabase.auth.getSession().then(({data:{session}})=>{setSession(session);setUser(session?.user??null);if(session?.user){const hydrated=hydrateCachedProfile(session.user.id);fetchProfile(session.user.id).finally(()=>setLoading(false));if(hydrated)setLoading(false);}else setLoading(false);});return()=>subscription.unsubscribe();},[]);
 useEffect(()=>{if(!user)return;const channel=supabase.channel(`auth-sync-${user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'user_permissions',filter:`user_id=eq.${user.id}`},()=>fetchPermissions(user.id)).on('postgres_changes',{event:'*',schema:'public',table:'user_roles',filter:`user_id=eq.${user.id}`},()=>fetchProfile(user.id)).subscribe();return()=>{supabase.removeChannel(channel);};},[user]);
 const signIn=async(email:string,password:string)=>{const{data,error}=await supabase.auth.signInWithPassword({email,password});if(error)return{error:error as Error|null};if(data.user){const{data:profileData,error:profileError}=await supabase.from('profiles').select('is_active').eq('user_id',data.user.id).maybeSingle();if(profileError){console.error('Error checking user status:',profileError);await supabase.auth.signOut();return{error:new Error('Erro ao verificar status do usuário')};}if(profileData&&!profileData.is_active){await supabase.auth.signOut();return{error:new Error('Usuário inativo. Entre em contato com o administrador.')}}}return{error:null};};
 const signOut=async()=>{setProfile(null);setActiveCompanyId(null);setSector(null);setAdditionalSectors([]);setRoles([]);setPermissions(null);await supabase.auth.signOut();};
 return <AuthContext.Provider value={{user,session,profile,sector,additionalSectors,allAccessibleSectorIds,roles,permissions,isAdmin,geralSectorId:GERAL_SECTOR_ID,loading,verifying,setVerifying,signIn,signOut,refreshProfile,refreshPermissions,canAccess,hasSectorAccess}}>{children}</AuthContext.Provider>;
}
export function useAuth(){const context=useContext(AuthContext);if(context===undefined)throw new Error('useAuth must be used within AuthProvider');return context;}
