import { useEffect, useMemo, useState } from 'react';
import { Users, Shield, KeyRound, Plus, Search, Trash2, Power, UserCog } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { MoreVertical } from 'lucide-react';
import { useAuth } from '@/contexts/AuthContext';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { UserRegistrationDialog } from '@/components/management/UserRegistrationDialog';
import { useIsMobile } from '@/hooks/use-mobile';

interface Profile { id:string; user_id:string; name:string; email:string; phone:string|null; address?:string|null; company:string|null; registration_number:string|null; profile_type:string; is_active:boolean; sector_id:string|null; birth_date:string|null; autonomy_level:string; }
interface Sector { id:string; name:string; color:string; }
interface Permission { user_id:string; can_post_announcements:boolean; can_delete_messages:boolean; can_access_management:boolean; can_access_password_change:boolean; can_create_war_room:boolean; can_access_bh:boolean; can_access_fechamento:boolean; can_access_orbs:boolean; }
interface Role { user_id:string; role:string; }

const ADMIN_EMAIL='adminservchat@servsul.com.br';

export function ManagementSection(){
 const {isAdmin,canAccess,profile,refreshPermissions}=useAuth(); const isMobile=useIsMobile(); const hasManagementAccess=isAdmin||['diretoria','gerente','supervisor','gestor'].includes(profile?.autonomy_level||'')||canAccess('can_access_management');
 const canChangePasswords=hasManagementAccess||canAccess('can_access_password_change');
 const [users,setUsers]=useState<Profile[]>([]); const [sectors,setSectors]=useState<Sector[]>([]); const [permissions,setPermissions]=useState<Record<string,Permission>>({}); const [roles,setRoles]=useState<Record<string,Role>>({}); const [search,setSearch]=useState(''); const [loading,setLoading]=useState(true); const [createOpen,setCreateOpen]=useState(false); const [passwordUser,setPasswordUser]=useState<Profile|null>(null); const [deleteUser,setDeleteUser]=useState<Profile|null>(null); const [newPassword,setNewPassword]=useState(''); const [saving,setSaving]=useState(false); const [editUser,setEditUser]=useState<Profile|null>(null); const [editName,setEditName]=useState(''); const [editPhone,setEditPhone]=useState(''); const [editBirth,setEditBirth]=useState('');
 const fetchData=async()=>{setLoading(true);try{const[{data:u,error:ue},{data:s,error:se},{data:p},{data:r}]=await Promise.all([supabase.rpc('admin_list_profiles_full'),supabase.from('sectors').select('*').order('name'),supabase.from('user_permissions').select('*'),supabase.from('user_roles').select('*')]);if(ue)throw ue;if(se)throw se;setUsers((u as any[])||[]);setSectors(s||[]);const pm:Record<string,Permission>={};(p||[]).forEach((x:any)=>pm[x.user_id]=x);setPermissions(pm);const rm:Record<string,Role>={};(r||[]).forEach((x:any)=>rm[x.user_id]=x);setRoles(rm);}catch(e){console.error(e);toast.error('Erro ao carregar usuários e configurações.');}finally{setLoading(false);}};
 useEffect(()=>{if(hasManagementAccess)fetchData();else setLoading(false);},[hasManagementAccess]);
 const filtered=useMemo(()=>users.filter(u=>u.name.toLowerCase().includes(search.toLowerCase())||u.email.toLowerCase().includes(search.toLowerCase())),[users,search]);
 const updatePermission=async(userId:string,key:keyof Permission,value:boolean)=>{const map:Record<string,string>={can_post_announcements:'canPostAnnouncements',can_delete_messages:'canDeleteMessages',can_access_management:'canAccessManagement',can_access_password_change:'canAccessPasswordChange',can_create_war_room:'canCreateWarRoom',can_access_bh:'canAccessBh',can_access_fechamento:'canAccessFechamento',can_access_orbs:'canAccessOrbs'};try{const response=await supabase.functions.invoke('update-user-permissions',{body:{userId,permissions:{[map[key]]:value}}});if(response.error||response.data?.error)throw new Error(response.data?.error||response.error?.message);setPermissions(prev=>({...prev,[userId]:{...prev[userId],user_id:userId,[key]:value} as Permission}));if(userId===profile?.user_id)await refreshPermissions();toast.success('Permissão salva.');}catch(e){console.error(e);toast.error(e instanceof Error?e.message:'Erro ao atualizar permissão');}};
 const updateStatus=async(u:Profile)=>{try{const{error}=await supabase.from('profiles').update({is_active:!u.is_active}).eq('user_id',u.user_id);if(error)throw error;setUsers(prev=>prev.map(x=>x.user_id===u.user_id?{...x,is_active:!u.is_active}:x));toast.success(`Usuário ${!u.is_active?'ativado':'desativado'}.`);}catch(e){toast.error('Erro ao atualizar status.');}};
 const openEdit=(u:Profile)=>{setEditUser(u);setEditName(u.name||'');setEditPhone(u.phone||'');setEditBirth(u.birth_date||'');};
 const saveEdit=async()=>{if(!editUser)return;setSaving(true);try{const{error}=await supabase.from('profiles').update({name:editName,phone:editPhone||null,birth_date:editBirth||null}).eq('user_id',editUser.user_id);if(error)throw error;toast.success('Usuário atualizado.');setEditUser(null);fetchData();}catch(e){toast.error('Erro ao atualizar usuário.');}finally{setSaving(false);}};
 const changePassword=async()=>{if(!passwordUser)return;if(!/^\d{6}$/.test(newPassword)){toast.error('A senha deve conter exatamente 6 dígitos numéricos.');return;}setSaving(true);try{const response=await supabase.functions.invoke('manage-user',{body:{type:'change-password',userId:passwordUser.user_id,newPassword}});if(response.error||response.data?.error)throw new Error(response.data?.error||response.error?.message);toast.success(`Senha de ${passwordUser.name} alterada.`);setPasswordUser(null);setNewPassword('');}catch(e){toast.error(e instanceof Error?e.message:'Erro ao alterar senha.');}finally{setSaving(false);}};
 const deleteUserPermanently=async()=>{if(!deleteUser)return;if(deleteUser.email===ADMIN_EMAIL){toast.error('O administrador principal não pode ser excluído.');return;}setSaving(true);try{const response=await supabase.functions.invoke('manage-user',{body:{type:'delete-single-user',userId:deleteUser.user_id}});if(response.error||response.data?.error)throw new Error(response.data?.error||response.error?.message);toast.success('Usuário excluído com sucesso.');setDeleteUser(null);fetchData();}catch(e){toast.error(e instanceof Error?e.message:'Erro ao excluir usuário.');}finally{setSaving(false);}};
 if(!hasManagementAccess)return <div className="flex h-full items-center justify-center p-6"><Card className="max-w-md"><CardContent className="pt-6 text-center"><Shield className="mx-auto h-12 w-12 text-muted-foreground"/><h2 className="mt-4 text-lg font-semibold">Acesso Restrito</h2><p className="mt-2 text-sm text-muted-foreground">Você não tem permissão para acessar esta área.</p></CardContent></Card></div>;
 return <div className="h-full overflow-auto p-4 md:p-6"><div className="space-y-5"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h1 className="flex items-center gap-2 text-xl font-bold md:text-2xl"><UserCog className="h-6 w-6"/>Gerenciamento</h1><p className="text-sm text-muted-foreground">Usuários, permissões, senhas e acesso ao sistema.</p></div><Button onClick={()=>setCreateOpen(true)} className="gap-2"><Plus className="h-4 w-4"/>Novo Usuário</Button></div>
 <Card><CardHeader className="pb-3"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><CardTitle>Usuários</CardTitle><CardDescription>{filtered.length} usuários encontrados</CardDescription></div><div className="relative w-full md:w-72"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar usuário..." className="pl-9"/></div></div></CardHeader><CardContent>{loading?<div className="py-12 text-center text-sm text-muted-foreground">Carregando...</div>:<div className="space-y-2">{filtered.map(u=>{const role=roles[u.user_id]?.role||'colaborador';const perm=permissions[u.user_id];const sector=sectors.find(s=>s.id===u.sector_id);return <div key={u.user_id} className="flex flex-col gap-3 rounded-xl border border-border p-3 md:flex-row md:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-medium">{u.name}</p><Badge variant="secondary">{role}</Badge><Badge variant={u.is_active?'default':'secondary'}>{u.is_active?'Ativo':'Inativo'}</Badge></div><p className="truncate text-xs text-muted-foreground">{u.email} • {sector?.name||'Sem setor'}</p></div><div className="flex flex-wrap items-center gap-1"><Button variant="ghost" size="sm" onClick={()=>openEdit(u)}>Editar</Button>{canChangePasswords&&<Button variant="ghost" size="sm" onClick={()=>setPasswordUser(u)}><KeyRound className="mr-1 h-4 w-4"/>Senha</Button>}<Button variant="ghost" size="icon" onClick={()=>updateStatus(u)} title={u.is_active?'Desativar':'Ativar'}><Power className="h-4 w-4"/></Button>{u.email!==ADMIN_EMAIL&&<Button variant="ghost" size="icon" className="text-destructive" onClick={()=>setDeleteUser(u)} title="Excluir"><Trash2 className="h-4 w-4"/></Button>}<DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon"><MoreVertical className="h-4 w-4"/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={()=>openEdit(u)}>Editar</DropdownMenuItem>{canChangePasswords&&<DropdownMenuItem onClick={()=>setPasswordUser(u)}>Alterar senha</DropdownMenuItem>}<DropdownMenuSeparator/><DropdownMenuItem onClick={()=>updateStatus(u)}>{u.is_active?'Desativar':'Ativar'}</DropdownMenuItem>{u.email!==ADMIN_EMAIL&&<DropdownMenuItem className="text-destructive" onClick={()=>setDeleteUser(u)}>Excluir usuário</DropdownMenuItem>}</DropdownMenuContent></DropdownMenu></div></div>})}</div>}</CardContent></Card>
 <Card><CardHeader><CardTitle>Permissões</CardTitle><CardDescription>As permissões individuais continuam sendo respeitadas, inclusive para usuários que não são administradores.</CardDescription></CardHeader><CardContent><div className="space-y-3">{filtered.map(u=>{const p=permissions[u.user_id]||({} as Permission);const admin=roles[u.user_id]?.role==='admin';return <div key={u.user_id} className="rounded-xl border p-3"><div className="mb-3 flex items-center justify-between"><div><p className="font-medium">{u.name}</p><p className="text-xs text-muted-foreground">{u.email}</p></div><Badge variant="outline">{admin?'Administrador':roles[u.user_id]?.role||'Colaborador'}</Badge></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><PermissionSwitch label="Gerenciamento" checked={admin||!!p.can_access_management} disabled={admin} onChange={v=>updatePermission(u.user_id,'can_access_management',v)}/><PermissionSwitch label="Alterar senhas" checked={admin||!!p.can_access_password_change} disabled={admin} onChange={v=>updatePermission(u.user_id,'can_access_password_change',v)}/><PermissionSwitch label="Excluir mensagens" checked={admin||!!p.can_delete_messages} disabled={admin} onChange={v=>updatePermission(u.user_id,'can_delete_messages',v)}/><PermissionSwitch label="Criar War Room" checked={admin||!!p.can_create_war_room} disabled={admin} onChange={v=>updatePermission(u.user_id,'can_create_war_room',v)}/></div></div>})}</div></CardContent></Card>
 <UserRegistrationDialog open={createOpen} onOpenChange={setCreateOpen} sectors={sectors} onSuccess={()=>{setCreateOpen(false);fetchData();}}/>
 <Dialog open={!!passwordUser} onOpenChange={o=>!o&&setPasswordUser(null)}><DialogContent className="max-w-sm"><DialogHeader><DialogTitle>Alterar senha</DialogTitle><DialogDescription>Defina uma nova senha de 6 dígitos para {passwordUser?.name}. A senha existente não é exibida, pois o sistema armazena credenciais de forma segura.</DialogDescription></DialogHeader><div className="space-y-4"><div className="space-y-2"><Label>Nova senha</Label><Input type="password" inputMode="numeric" maxLength={6} value={newPassword} onChange={e=>setNewPassword(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="6 dígitos"/></div><Button className="w-full" onClick={changePassword} disabled={saving}>{saving?'Salvando...':'Alterar senha'}</Button></div></DialogContent></Dialog>
 <Dialog open={!!deleteUser} onOpenChange={o=>!o&&setDeleteUser(null)}><DialogContent className="max-w-sm"><DialogHeader><DialogTitle>Excluir usuário</DialogTitle><DialogDescription>Excluir permanentemente <strong>{deleteUser?.name}</strong> remove o acesso e os dados vinculados ao usuário. Esta ação não pode ser desfeita.</DialogDescription></DialogHeader><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setDeleteUser(null)}>Cancelar</Button><Button variant="destructive" onClick={deleteUserPermanently} disabled={saving}>{saving?'Excluindo...':'Excluir definitivamente'}</Button></div></DialogContent></Dialog>
 <Dialog open={!!editUser} onOpenChange={o=>!o&&setEditUser(null)}><DialogContent className="max-w-md"><DialogHeader><DialogTitle>Editar usuário</DialogTitle><DialogDescription>Atualize informações básicas do usuário.</DialogDescription></DialogHeader><div className="space-y-4"><div className="space-y-2"><Label>Nome</Label><Input value={editName} onChange={e=>setEditName(e.target.value)}/></div><div className="space-y-2"><Label>Telefone</Label><Input value={editPhone} onChange={e=>setEditPhone(e.target.value)}/></div><div className="space-y-2"><Label>Data de nascimento</Label><Input type="date" value={editBirth} onChange={e=>setEditBirth(e.target.value)}/></div><Button className="w-full" onClick={saveEdit} disabled={saving}>{saving?'Salvando...':'Salvar alterações'}</Button></div></DialogContent></Dialog>
 </div></div>;
}
function PermissionSwitch({label,checked,disabled,onChange}:{label:string;checked:boolean;disabled?:boolean;onChange:(value:boolean)=>void}){return <div className="flex items-center justify-between gap-2 rounded-lg bg-muted/40 p-2"><span className="text-xs">{label}</span><Switch checked={checked} disabled={disabled} onCheckedChange={onChange}/></div>}
